@extends('layouts/layoutMaster')
@php $isFlex = true; $isFooter = false; $tipoInicial = old('tipo_contrato', 'PME'); @endphp
@section('title', 'Comercial - Nova Proposta')
@section('vendor-style') @vite(['resources/assets/vendor/libs/sweetalert2/sweetalert2.scss','resources/assets/vendor/libs/select2/select2.scss','resources/assets/vendor/libs/flatpickr/flatpickr.scss','resources/assets/vendor/libs/animate-css/animate.scss']) @endsection
@section('page-style') @vite(['resources/assets/vendor/scss/pages/nova-proposta.scss']) @endsection
@section('vendor-script') @vite(['resources/assets/vendor/libs/sweetalert2/sweetalert2.js','resources/assets/vendor/libs/select2/select2.js','resources/assets/vendor/libs/flatpickr/flatpickr.js','resources/assets/vendor/libs/cleavejs/cleave.js','resources/assets/vendor/libs/cleavejs/cleave-phone.js']) @endsection
@section('page-script') @vite(['resources/assets/js/novaProposta.js']) @endsection

@section('content')
<div class="nova-proposta-wrapper np-wizard-shell">
  <header class="np-top-header">
    <div class="top-header-left"><a href="{{ route('comercial.openClient', $client->id) }}" class="btn-back" aria-label="Voltar ao cliente"><svg viewBox="0 0 24 24"><path d="m15 18-6-6 6-6"/></svg></a><div class="top-header-info"><span class="header-badge">{{ $tipoInicial }}</span><h1 class="page-title">Nova proposta</h1></div></div>
    <div class="top-header-client"><div class="client-avatar"><svg viewBox="0 0 24 24"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg></div><div class="client-details"><span class="client-name">{{ $client->nome_cliente }}</span><span class="client-contact">{{ $client->telefone1 }} @if($client->email) · {{ $client->email }} @endif</span></div></div>
    <button type="button" class="btn-docs-checklist" id="btn-open-docs-modal"><svg viewBox="0 0 24 24"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8M8 17h8"/></svg><span>Checklist</span></button>
  </header>

  <nav class="np-steps" aria-label="Etapas do cadastro"><ol>
    @foreach ([1=>['Identificação','Tipo e contratante'],2=>['Venda','Operadora e valores'],3=>['Beneficiários','Grupos familiares'],4=>['Portabilidade','Origem e destino'],5=>['Documentos','Revisão e envio']] as $n => [$titulo,$sub])
      <li class="np-step {{ $n === 1 ? 'is-active' : '' }}" data-step-indicator="{{ $n }}" aria-label="Etapa {{ $n }} de 5: {{ $titulo }}{{ $n === 1 ? ', atual' : '' }}" @if($n===1) aria-current="step" @endif><span class="np-step-number"><span>{{ $n }}</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m7 12 3 3 7-7"/></svg></span><span class="np-step-copy"><strong>{{ $titulo }}</strong><small>{{ $sub }}</small></span></li>
    @endforeach
  </ol></nav>

  <form method="POST" action="{{ route('comercial.createSale') }}" class="np-form" id="formNovaProposta" novalidate>
    @csrf
    <input type="hidden" id="contato_id" name="contato_id" value="{{ $client->id }}"><input type="hidden" id="tipo_contrato" name="tipo_contrato" value="{{ $tipoInicial }}"><input type="hidden" id="qtd_titulares" name="qtd_titulares" value="1"><input type="hidden" id="vidas" name="vidas" value="0">
    <div class="np-wizard-layout"><main class="np-wizard-main">
      <section class="np-step-panel is-active" data-step-panel="1" aria-labelledby="np-step-1-title">
        <header class="np-panel-heading"><h2 id="np-step-1-title" tabindex="-1">Quem está contratando?</h2><p>Escolha o tipo da proposta e confirme os dados oficiais.</p></header>
        <fieldset class="np-choice-fieldset"><legend class="visually-hidden">Tipo da proposta</legend>
          <label class="np-type-choice"><input type="radio" name="tipo_proposta_escolha" value="PME" {{ $tipoInicial==='PME'?'checked':'' }}><span><strong>PME</strong><small>Contrato empresarial com CNPJ</small></span></label>
          <label class="np-type-choice"><input type="radio" name="tipo_proposta_escolha" value="ADESAO" {{ $tipoInicial==='ADESAO'?'checked':'' }}><span><strong>Adesão</strong><small>Contrato individual com CPF</small></span></label>
        </fieldset>
        <select id="tipo_proposta_toggle" class="visually-hidden" tabindex="-1"><option value="PME" {{ $tipoInicial==='PME'?'selected':'' }}>PME</option><option value="ADESAO" {{ $tipoInicial==='ADESAO'?'selected':'' }}>ADESAO</option></select>
        <div class="np-section np-identity-card"><div class="section-body"><div class="np-grid grid-2">
          <div class="np-field"><label id="label-cpf-cnpj" class="required" for="cpf_cnpj">{{ $tipoInicial==='ADESAO'?'CPF':'CNPJ' }}</label><div class="np-enriched-input"><input type="text" id="cpf_cnpj" name="cpf_cnpj" class="np-input" value="{{ old('cpf_cnpj') }}" required autocomplete="off"><span class="np-lookup-spinner"></span></div><p class="np-lookup-status" data-lookup-status-for="cpf_cnpj" role="status" aria-live="polite">Digite um documento válido para localizar os dados.</p></div>
          <div class="np-field"><label id="label-razao-social" class="required" for="nome_contrato">{{ $tipoInicial==='ADESAO'?'Nome completo':'Razão social' }}</label><input type="text" id="nome_contrato" name="nome_contrato" class="np-input" value="{{ old('nome_contrato') }}" required></div>
          <div class="np-field" id="field-tipo-empresa" {{ $tipoInicial==='ADESAO'?'hidden':'' }}><label class="required" for="tipo_empresa">Tipo de empresa</label><select id="tipo_empresa" name="tipo_empresa" class="np-input"><option value="">Selecione...</option>@foreach(['MEI','ME','EPP','LTDA','SA','EIRELI','SLU'] as $tipo)<option value="{{ $tipo }}" {{ old('tipo_empresa')===$tipo?'selected':'' }}>{{ $tipo==='SA'?'S/A':$tipo }}</option>@endforeach</select></div>
          <div class="np-field" id="field-data-abertura" {{ $tipoInicial==='ADESAO'?'hidden':'' }}><label for="data_abertura">Data de abertura</label><input type="text" id="data_abertura" name="data_abertura" class="np-input flatpickr-date" value="{{ old('data_abertura') }}" placeholder="DD/MM/AAAA"></div>
          <div class="np-field"><label for="email">E-mail</label><input type="email" id="email" name="email" class="np-input" value="{{ old('email') }}"></div><div class="np-field"><label for="telefone1">Telefone principal</label><input type="text" id="telefone1" name="telefone1" class="np-input mask-telefone" value="{{ old('telefone1') }}"></div><div class="np-field"><label for="telefone2">Outro telefone</label><input type="text" id="telefone2" name="telefone2" class="np-input mask-telefone" value="{{ old('telefone2') }}"></div>
        </div><div class="np-data-disclaimer"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="M12 11v5M12 8h.01"/></svg><p><strong>Confira antes de continuar.</strong> A consulta ajuda no preenchimento, mas as informações enviadas precisam estar corretas e podem ser editadas.</p></div></div></div>
      </section>

      <section class="np-step-panel" data-step-panel="2" aria-labelledby="np-step-2-title" hidden>
        <header class="np-panel-heading"><h2 id="np-step-2-title" tabindex="-1">O que foi vendido?</h2><p>Separe o produto contratado das condições comerciais da venda.</p></header>
        <div class="np-sale-card-grid">
          <section class="np-section np-sale-card" aria-labelledby="np-product-card-title">
            <header class="np-sale-card-header"><span class="np-sale-card-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 7h16M6 3h12a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Z"/><path d="M8 12h8M8 16h5"/></svg></span><div><h3 id="np-product-card-title">Produto vendido</h3><p>Identifique a operadora e os benefícios incluídos.</p></div></header>
            <div class="section-body np-sale-fields">
              <div class="np-field"><label class="required" for="operadora">Operadora vendida</label><select id="operadora" name="operadora_id" class="np-input"><option value="">Selecione...</option>@foreach($operadoras as $op)<option value="{{ $op->id }}" data-nome="{{ strtoupper($op->nome) }}" {{ old('operadora_id')==$op->id?'selected':'' }}>{{ strtoupper($op->nome) }}</option>@endforeach</select></div>
              <div class="np-field"><label for="plano_dental">Plano dental incluído?</label><select id="plano_dental" name="plano_dental" class="np-input"><option value="SIM" {{ old('plano_dental','SIM')==='SIM'?'selected':'' }}>Sim</option><option value="NAO" {{ old('plano_dental')==='NAO'?'selected':'' }}>Não</option></select></div>
            </div>
          </section>
          <section class="np-section np-sale-card" aria-labelledby="np-values-card-title">
            <header class="np-sale-card-header"><span class="np-sale-card-icon np-sale-card-icon-money" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 10h.01M17 14h.01"/><circle cx="12" cy="12" r="2"/></svg></span><div><h3 id="np-values-card-title">Valores da venda</h3><p>Registre a mensalidade e a angariação combinada.</p></div></header>
            <div class="section-body np-sale-fields">
              <div class="np-field"><label class="required" for="valor_contrato">Valor mensal do contrato</label><input type="text" id="valor_contrato" name="valor_contrato" value="{{ old('valor_contrato') }}" class="np-input monetary-field" placeholder="R$ 0,00"></div>
              <div class="np-field"><label class="required" for="angariacao_status">Possui angariação?</label><select id="angariacao_status" name="angariacao_status" class="np-input"><option value="NAO" {{ old('angariacao_status','NAO')==='NAO'?'selected':'' }}>Não</option><option value="SIM" {{ old('angariacao_status')==='SIM'?'selected':'' }}>Sim</option></select></div>
              <div class="np-field" id="field-taxa-angariacao" hidden><label class="required" for="taxa_angariacao">Valor da angariação</label><input type="text" id="taxa_angariacao" name="taxa_angariacao" value="{{ old('taxa_angariacao') }}" class="np-input monetary-field" placeholder="R$ 0,00"></div>
            </div>
          </section>
        </div>
      </section>

      <section class="np-step-panel" data-step-panel="3" aria-labelledby="np-step-3-title" hidden>
        <header class="np-panel-heading np-panel-heading-action"><div><h2 id="np-step-3-title" tabindex="-1">Monte os grupos familiares</h2><p>Todo dependente deve ficar dentro do grupo do seu titular.</p></div><div class="np-add-titular-control"><button type="button" class="btn-add-titular-main" id="btn-add-titular" aria-describedby="np-add-titular-hint" disabled><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>Adicionar titular</button><span id="np-add-titular-hint" role="status">Complete o titular atual para adicionar outro.</span></div></header>
        <div class="np-group-guide"><span>1</span><p><strong>Comece pelo titular</strong><small>Depois adicione dependentes ou outro titular.</small></p><span>2</span><p><strong>Revise o vínculo</strong><small>O recuo mostra a qual titular cada dependente pertence.</small></p></div><div id="titulares-container" class="titulares-scroll"></div>
      </section>

      <section class="np-step-panel" data-step-panel="4" aria-labelledby="np-step-4-title" hidden>
        <header class="np-panel-heading"><h2 id="np-step-4-title" tabindex="-1">Esta proposta possui portabilidade?</h2><p>Informe de onde cada pessoa vem e para qual plano irá.</p></header>
        <fieldset class="np-choice-fieldset np-choice-compact"><legend class="visually-hidden">Possui portabilidade</legend><label class="np-type-choice"><input type="radio" name="tem_portabilidade_escolha" value="NAO" checked><span><strong>Não</strong><small>Seguir sem portabilidade</small></span></label><label class="np-type-choice"><input type="radio" name="tem_portabilidade_escolha" value="SIM"><span><strong>Sim</strong><small>Cadastrar pessoas</small></span></label></fieldset>
        <div id="np-portabilidade-stage" hidden><x-proposta-portabilidades :operadoras="$operadoras" /></div>
      </section>

      <section class="np-step-panel" data-step-panel="5" aria-labelledby="np-step-5-title" hidden>
        <header class="np-panel-heading"><h2 id="np-step-5-title" tabindex="-1">Revise e envie os documentos</h2><p>Os arquivos são opcionais e podem ser anexados depois.</p></header>
        <div class="np-documents-context"><div><span>Contratante</span><strong id="np-resumo-empresa">—</strong></div><div><span>Operadora</span><strong id="np-resumo-operadora">—</strong></div><div><span>Beneficiários</span><strong id="np-resumo-vidas">0 vidas</strong></div></div>
        <section class="np-section np-observations-card" aria-labelledby="np-observations-title"><header class="np-sale-card-header"><span class="np-sale-card-icon np-sale-card-icon-notes" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 4h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H9l-4 3v-3a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2Z"/><path d="M8 9h8M8 13h5"/></svg></span><div><h3 id="np-observations-title">Observações para o pós-venda</h3><p>Inclua orientações ou informações importantes para a execução da proposta.</p></div></header><div class="section-body"><div class="np-field"><label for="obs_contrato">Observações</label><textarea id="obs_contrato" name="obs_contrato" class="np-input" rows="4" maxlength="10000" placeholder="Ex.: condição acordada, prazo ou orientação para o atendimento">{{ old('obs_contrato') }}</textarea></div></div></section>
        <section class="np-section np-documents" id="np-documentos-destino"><div class="section-body"><div class="np-documents-intro"><div><strong>Documentos da venda</strong><p>PDF ou imagem, até 25 MB por arquivo.</p></div><span class="np-documents-optional">Opcional</span></div><p class="np-files-refresh-note">Mantenha esta página aberta durante o envio.</p><input id="documentos-venda" type="file" multiple accept="application/pdf,image/*" class="visually-hidden" aria-describedby="documentos-ajuda documentos-status"><div class="np-dropzone" id="documentos-dropzone"><span class="np-dropzone-icon"><svg viewBox="0 0 24 24"><path d="m16 16-4-4-4 4M12 12v9M20 17.5A5 5 0 0 0 18 8h-1.3A8 8 0 1 0 3 16"/></svg></span><div class="np-dropzone-copy"><strong>Arraste os documentos</strong><span>ou escolha no seu dispositivo</span></div><button type="button" class="np-dropzone-action" id="documentos-selecionar">Selecionar arquivos</button><div class="np-dropzone-rules"><span>PDF ou imagem</span><span>Máximo de 30</span></div></div><p id="documentos-ajuda" class="visually-hidden">PDF e imagens. Máximo de 30 arquivos e 25 MB por arquivo.</p><div id="documentos-status" class="np-documents-status" role="status" aria-live="polite"></div><div class="np-documents-summary" id="documentos-resumo" hidden><div><strong id="documentos-resumo-quantidade">0 arquivos</strong><span id="documentos-resumo-tamanho">0 MB</span></div><button type="button" id="documentos-limpar">Limpar seleção</button></div><ul id="documentos-lista" class="np-documents-list"></ul></div></section>
        <button type="button" class="np-guide-button" id="btn-open-docs-modal-step">Ver checklist de documentos</button>
      </section>
    </main>

    <aside class="np-live-summary" aria-labelledby="np-summary-title"><h2 id="np-summary-title">Resumo da proposta</h2><dl><div><dt>Tipo</dt><dd id="np-summary-type">{{ $tipoInicial }}</dd></div><div><dt>Contratante</dt><dd id="np-summary-name">Ainda não informado</dd></div><div><dt>Operadora</dt><dd id="np-summary-operator">Ainda não informada</dd></div><div><dt>Valor mensal</dt><dd id="np-summary-value">R$ 0,00</dd></div><div><dt>Grupos</dt><dd><span id="total-titulares">0</span> titulares · <span id="total-dependentes">0</span> dependentes</dd></div><div><dt>Total</dt><dd><span id="total-vidas">0</span> vidas</dd></div></dl><p><span class="np-summary-dot"></span>Rascunho salvo automaticamente</p></aside></div>

    <div class="np-step-actions" aria-label="Navegação entre etapas"><button type="button" class="np-action np-action-secondary" id="np-voltar-etapa" hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m15 18-6-6 6-6"/></svg><span>Voltar</span></button><div class="np-step-actions-end"><button type="button" class="np-action np-action-ghost" id="np-concluir-sem-documentos" hidden>Concluir sem documentos</button><button type="button" class="np-action np-action-primary" id="np-avancar-etapa"><span>Continuar</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m9 18 6-6-6-6"/></svg></button><button type="submit" class="np-action np-action-primary" id="np-finalizar-venda" hidden><span>Salvar venda e enviar documentos</span></button><a class="np-action np-action-ghost" id="np-ir-vendas" href="{{ route('sale.listSale') }}" hidden>Ir para minhas vendas</a></div></div>
  </form>
</div>

<template id="template-titular"><article class="titular-card" data-titular-index="__INDEX__"><header class="titular-header"><div class="titular-badge"><span class="badge-number">__NUMBER__</span><span class="badge-text">Titular</span></div><span class="titular-completion" role="status">Preencha os campos obrigatórios</span><div class="titular-actions"><button type="button" class="btn-action btn-add-dep" disabled><svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg><span>Dependente</span></button><button type="button" class="btn-action btn-remove-titular" aria-label="Remover titular"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button></div></header><div class="titular-body">
  <div class="field-row"><div class="np-field"><label class="required" for="titular-__INDEX__-cpf">CPF</label><div class="np-enriched-input"><input id="titular-__INDEX__-cpf" type="text" name="titulares[__INDEX__][cpf]" class="np-input mask-cpf js-documento-pessoa"><span class="np-lookup-spinner"></span></div><p class="np-lookup-status" role="status"></p></div><div class="np-field"><label class="required" for="titular-__INDEX__-nome">Nome completo</label><input id="titular-__INDEX__-nome" type="text" name="titulares[__INDEX__][nome]" class="np-input"></div></div>
  <div class="field-row"><div class="np-field"><label class="required" for="titular-__INDEX__-nascimento">Data de nascimento</label><input id="titular-__INDEX__-nascimento" type="text" name="titulares[__INDEX__][data_nascimento]" class="np-input flatpickr-nascimento" placeholder="DD/MM/AAAA"></div><div class="np-field"><label class="required" for="titular-__INDEX__-email">E-mail</label><input id="titular-__INDEX__-email" type="email" name="titulares[__INDEX__][email]" class="np-input"></div></div>
  <div class="field-row"><div class="np-field"><label class="required" for="titular-__INDEX__-telefone1">Telefone principal</label><input id="titular-__INDEX__-telefone1" type="text" name="titulares[__INDEX__][telefone1]" class="np-input mask-telefone"></div><div class="np-field"><label for="titular-__INDEX__-telefone2">Outro telefone</label><input id="titular-__INDEX__-telefone2" type="text" name="titulares[__INDEX__][telefone2]" class="np-input mask-telefone"></div></div>
  <div class="field-row"><div class="np-field field-cargo-wrapper"><label class="required" for="titular-__INDEX__-cargo">Cargo</label><select id="titular-__INDEX__-cargo" name="titulares[__INDEX__][cargo]" class="np-input select-cargo-titular"><option value="">Selecione...</option>@foreach(['SOCIO'=>'Sócio','DIRETOR'=>'Diretor','GERENTE'=>'Gerente','FUNCIONARIO'=>'Funcionário','PRESTADOR'=>'Prestador','ESTAGIARIO'=>'Estagiário'] as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></div><div class="np-field"><label class="required" for="titular-__INDEX__-plano">Plano</label><select id="titular-__INDEX__-plano" name="titulares[__INDEX__][plano_id]" class="np-input select-plano-titular"><option value="">Selecione a operadora primeiro</option></select></div></div>
  <div class="field-row"><div class="np-field"><label class="required" for="titular-__INDEX__-copart">Coparticipação</label><select id="titular-__INDEX__-copart" name="titulares[__INDEX__][coparticipacao]" class="np-input select-coparticipacao-titular"><option value="">Selecione...</option></select></div><div class="np-field"><label class="required" for="titular-__INDEX__-anterior">Possui plano anterior?</label><select id="titular-__INDEX__-anterior" name="titulares[__INDEX__][plano_anterior]" class="np-input select-plano-anterior-titular"><option value="NAO">Não</option><option value="SIM">Sim</option></select></div></div>
  <div class="field-row field-row-op-anterior" hidden><div class="np-field"><label class="required">Operadora anterior</label><select name="titulares[__INDEX__][operadora_anterior_id]" class="np-input field-op-anterior-titular"><option value="">Selecione...</option>@foreach($operadoras as $op)<option value="{{ $op->id }}">{{ strtoupper($op->nome) }}</option>@endforeach</select></div><label class="np-check-cancelamento"><input type="checkbox" name="titulares[__INDEX__][precisa_cancelamento]" value="1"><span>Solicitar cancelamento do plano anterior</span></label></div>
</div><div class="dependentes-container" data-titular-index="__INDEX__"></div></article></template>

<div class="dep-modal-overlay" id="dep-modal-overlay" aria-hidden="true"><div class="dep-modal" role="dialog" aria-modal="true" aria-labelledby="dep-modal-title"><header class="dep-modal-header"><div class="dep-modal-title"><h3 id="dep-modal-title">Adicionar dependente</h3><span>O dependente ficará no grupo selecionado.</span></div><button type="button" class="dep-modal-close" id="btn-dep-modal-close" aria-label="Fechar"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button></header><div class="dep-modal-body"><div class="np-grid grid-2">
  <div class="np-field"><label class="required" for="dep_cpf">CPF</label><div class="np-enriched-input"><input type="text" id="dep_cpf" class="np-input js-documento-pessoa"><span class="np-lookup-spinner"></span></div><p class="np-lookup-status" data-lookup-status-for="dep_cpf" role="status"></p></div><div class="np-field"><label class="required" for="dep_nome">Nome completo</label><input type="text" id="dep_nome" class="np-input"></div>
  <div class="np-field"><label class="required" for="dep_data_nascimento">Data de nascimento</label><input type="text" id="dep_data_nascimento" class="np-input" placeholder="DD/MM/AAAA"></div><div class="np-field"><label class="required" for="dep_parentesco">Parentesco</label><select id="dep_parentesco" class="np-input"><option value="">Selecione...</option>@foreach(['CONJUGE'=>'Cônjuge','COMPANHEIRO'=>'Companheiro(a)','FILHO'=>'Filho(a)','ENTEADO'=>'Enteado(a)','PAI_MAE'=>'Pai/Mãe','SOGRO'=>'Sogro(a)','IRMAO'=>'Irmão(ã)','NETO'=>'Neto(a)','AVO'=>'Avô/Avó','BISNETO'=>'Bisneto(a)','BISAVO'=>'Bisavô/Bisavó','TIO'=>'Tio(a)','SOBRINHO'=>'Sobrinho(a)','PRIMO'=>'Primo(a)','GENRO_NORA'=>'Genro/Nora','CUNHADO'=>'Cunhado(a)','TUTELADO'=>'Tutelado(a)','OUTROS'=>'Outros'] as $v=>$l)<option value="{{ $v }}">{{ $l }}</option>@endforeach</select></div>
  <div class="np-field"><label class="required" for="dep_email">E-mail</label><input type="email" id="dep_email" class="np-input"></div><div class="np-field"><label class="required" for="dep_telefone1">Telefone principal</label><input type="text" id="dep_telefone1" class="np-input"></div><div class="np-field"><label for="dep_telefone2">Outro telefone</label><input type="text" id="dep_telefone2" class="np-input"></div>
  <label class="np-inherit-plan span-2"><input type="checkbox" id="dep_herda_plano" checked><span><strong>Usar plano e coparticipação do titular</strong><small>Acompanha alterações feitas no titular.</small></span></label><div class="np-field"><label class="required" for="dep_plano_id">Plano</label><select id="dep_plano_id" class="np-input"></select></div><div class="np-field"><label class="required" for="dep_coparticipacao">Coparticipação</label><select id="dep_coparticipacao" class="np-input"><option value="">Selecione...</option><option value="Y">Sim</option><option value="N">Não</option><option value="PARCIAL">Parcial</option><option value="COMPLETA">Completa</option></select></div>
  <div class="np-field"><label class="required" for="dep_plano_anterior">Possui plano anterior?</label><select id="dep_plano_anterior" class="np-input"><option value="NAO">Não</option><option value="SIM">Sim</option></select></div><div class="np-field" id="dep-op-anterior-row" hidden><label class="required" for="dep_operadora_anterior_id">Operadora anterior</label><select id="dep_operadora_anterior_id" class="np-input"><option value="">Selecione...</option>@foreach($operadoras as $op)<option value="{{ $op->id }}">{{ strtoupper($op->nome) }}</option>@endforeach</select></div>
</div><p class="port-modal-error" id="dep-modal-error" hidden></p></div><footer class="dep-modal-footer"><button type="button" class="dep-btn dep-btn-ghost" id="btn-dep-modal-cancel">Cancelar</button><button type="button" class="dep-btn dep-btn-primary" id="btn-dep-modal-save"><span id="dep-modal-save-label">Adicionar dependente</span></button></footer></div></div>

<div class="docs-modal-overlay" id="docs-modal-overlay" aria-hidden="true"><div class="docs-modal" role="dialog" aria-modal="true" aria-labelledby="docs-modal-heading" tabindex="-1"><header class="docs-modal-header"><div class="docs-modal-title"><h3 id="docs-modal-heading">Checklist de documentação</h3><span>Confira a legibilidade antes do envio.</span></div><button type="button" class="docs-modal-close" id="btn-close-docs-modal" aria-label="Fechar"><svg viewBox="0 0 24 24"><path d="m18 6-12 12M6 6l12 12"/></svg></button></header><div class="docs-modal-body docs-two-columns"><section class="docs-column"><h4>Titular ou sócio</h4><ul><li>RG ou CNH e CPF</li><li>Comprovante de endereço recente</li><li>Contrato social e cartão CNPJ para PME</li><li>Carteirinha e carta de permanência, se aplicável</li></ul></section><section class="docs-column"><h4>Dependentes</h4><ul><li>RG ou CNH e CPF</li><li>Certidão de nascimento para menor sem RG</li><li>Comprovação de vínculo quando aplicável</li><li>Carteirinha e carta de permanência, se aplicável</li></ul></section></div></div></div>

<script>
window.oldTitulares=@json(old('titulares',[])); window.oldOperadoraId=@json(old('operadora_id')); window.oldPortabilidades=@json(old('portabilidades',[])); window.portabilidadePlanos=@json($planosPortabilidade);
window.clientData={nome:@json($client->nome_cliente??''),cpf:@json($client->cpf??''),email:@json($client->email??''),telefone1:@json($client->telefone1??''),telefone2:@json($client->telefone2??'')}; window.propostaLookupUrl=@json(route('comercial.proposta.consultaDocumento')); window.pageFlash={status:@json(session('status')),message:@json(session('message'))}; window.pageErrors=@json($errors->all());
document.addEventListener('DOMContentLoaded',()=>{const o=document.getElementById('docs-modal-overlay'),d=o?.querySelector('[role="dialog"]');let t;const close=()=>{o?.classList.remove('docs-modal-open');o?.setAttribute('aria-hidden','true');document.body.style.overflow='';t?.focus()};const open=()=>{t=document.activeElement;o?.classList.add('docs-modal-open');o?.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';d?.focus()};document.getElementById('btn-open-docs-modal')?.addEventListener('click',open);document.getElementById('btn-close-docs-modal')?.addEventListener('click',close);o?.addEventListener('click',e=>{if(e.target===o)close()});document.addEventListener('keydown',e=>{if(!o?.classList.contains('docs-modal-open'))return;if(e.key==='Escape')close();if(e.key==='Tab'){const f=Array.from(o.querySelectorAll('button:not(:disabled),a[href]')),first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}})});
</script>
@endsection
